### PR TITLE
org.geojson.MultiPolygon for geofencing zones

### LINKED ISSUE #58: Return nicer types for geofencing multi-polygons
Right now the geofencing multipolygons are returned in quite an awkward type: `List<List<List<List<Double>>>>`

Since I'm planning to implement geofencing zones in OTP I was wondering if we could return a type like `org.geojson.MultiPolygon` from https://github.com/opendatalab-de/geojson-jackson.

The problem is that there appears to be not an easy way to override the generated java type unless you add it to the JSON schema. It's would only be a very small change to the schema but feels a bit dirty.

What do you think, @testower?

cc @hannesj

### PR DESCRIPTION
**Pull request by leonardehrenfried**
Fixes #58 

This is how `customRuleFactory` works in theory but the separate maven project which you refer to by a system path plugin dependency is less than ideal.

Do you have a suggestion how to improve it?

I think you could make it a multi-module maven project, where you depend on the one of the modules in a plugin dependencies section but I'm not sure that's what you want. 

After looking at this code, maybe adding it to the source schema would not be so bad after all.

WDYT?

### CODE REVIEW

**Comment by testower** [comment]
That makes sense - thanks. I'll have to think about it.

Other than that, what seems to be the improvement from the API point of view? Could you demonstrate?

**Comment by leonardehrenfried** [comment]
In OTP it's quite easy to convert org.geojson.MultiPolygon to a JTS geometry with which we can actually write some routing code.

Here is the conversion: https://github.com/opentripplanner/OpenTripPlanner/blob/4fbe1946c276827bc7ffac9ec66e1935a52deb7e/src/main/java/org/opentripplanner/updater/vehicle_rental/datasources/GbfsVehicleRentalDataSource.java#L166-L174

**Comment by testower** [comment]
Nice! I'm happy to merge this as is if it works, and we can improve later if needed.

**Comment by leonardehrenfried** [comment]
Right now you have to cd into the subfolder and run `mvn package` manually to produce the jar. Do we want to somehow automated this or commit the compiled jar to git?

Just throwing out another idea: since all we do is to add the property `existingJavaType` we could potentially also do that with a tool like `jq` after downloading the schema files.

**Comment by testower** [comment]
> Right now you have to cd into the subfolder and run mvn package manually to produce the jar. Do we want to somehow automated this or commit the compiled jar to git?

Right, so that must be dealt with. For now maybe adding the jar is the fastest way forward.

> Just throwing out another idea: since all we do is to add the property existingJavaType we could potentially also do that with a tool like jq after downloading the schema files.

Yeah the thought did cross my mind, I just fear it's a slippery-hackety road .... 😬

**Comment by leonardehrenfried** [comment]
Do you have the stomach to convert the project to a maven multi-module project? 

If not then I will commit the compiled jar even though it's dirty.

**Comment by testower** [comment]
Let's go with the jar for now, and I'll add to my list to clean it up. Maybe create a new issue for it?

**Comment by leonardehrenfried** [comment]
I've committed the jar to repo. This is ready for review.

**Comment by leonardehrenfried** [comment]
@testower Did you manage to fix the build? Does it have something to do with this PR or is it unrelated?

**Comment by testower** [comment]
@leonardehrenfried sorry for the delay. I don't think it's related to the PR, but I have not had time to look into it yet. It will have to wait until next week I'm afraid :/

**Comment by leonardehrenfried** [comment]
Ok, thanks for the update and for this project.

**Comment by testower** [comment]
@leonardehrenfried seems to have been a blip in the artifactory. I'm going to update the PR with a major bump in the snapshot version before I merge this

**Pull request merged**
